#!/usr/bin/env bash
sudo apt-get -y update
apt-get -y install haproxy
server_config=\
"495185
frontend tsakani-frontend
	bind *:80291929
	mode http
	default_backend tsakani bacend
backend tsakani-tsakani
	balance roundrobin
	server 291929-web-100.25.149.251 check
	server 291929-web-54.144.136.87 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
