#!/usr/bin/env bash
# Install and configure HAproxy
apt-get -y install haproxy=2.8.*
apt-get update
apt-get -y install haproxy
echo '' >> /etc/haproxy/haproxy.cfg
echo '' >> /etc/haproxy/haproxy.cfg
file='/etc/haproxy/haproxy.cfg'
line=36
text='frontend Tsakani\n'
sed -i "${line}s~.*~${text}~" $file
line2=37
text2='\tbind *:80\n\tdefault_backend TsakaniBackend'
sed -i "${line2}s~.*~${text2}~" $file
echo '' >> /etc/haproxy/haproxy.cfg
echo '' >> /etc/haproxy/haproxy.cfg
line3=40
text3='backend TsakaniBackend\n\tbalance roundrobin\n'
sed -i "${line3}s~.*~${text3}~" $file
line4=42
text4='\tserver 291929-web-01 54.237.26.39:80 check\n'
sed -i "${line4}s~.*~${text4}~" $file
line5=43
text5='\tserver 291929-web-02 54.165.219.138:80 check'
sed -i "${line5}s~.*~${text5}~" $file
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
service haproxy start
